name: CI/CD Pipeline

on:
  push:
    branches: ["main"]  # run when code is pushed to main
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up JDK (optional for tests outside Docker)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Run tests (inside GitHub runner, not Docker)
      - name: Run Maven tests
        run: mvn test

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: SonarQube Scan
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=Mohd-Elham_testing-cicd-one \
            -Dsonar.organization=mohd-elham \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      

      # 4. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Build Docker image (multi-stage Dockerfile)
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest .

      # 6. Push Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest
